# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Main Branch Validations
on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 14 * * 2' # 2pm UTC each Tuesday
jobs:
  MAIN-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
        check-latest: true
    - uses: psf/black@stable
      with:
        options: "--check --diff --verbose --exclude=\"third_party/.*\""
    - name: Run Tests and Validate JSON
      run: |
        pip3 install -r requirements.txt
        python3 tests/rws_tests.py
        python3 check_sites.py -i related_website_sets.JSON --with_diff --strict_formatting > results.txt
    - name: Read Results
      id: read_results
      uses: andstor/file-reader-action@v1
      with:
        path: "results.txt"
    - name: Record Failure
      if: steps.read_results.outputs.contents != 'success'
      uses: actions/github-script@v3
      with:
        script: core.setFailed('This run has failed.')
