name: Pull Request Validations
on: pull_request_target
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.read_results.outputs.contents }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
        check-latest: true
    - name: Run Tests and Validate JSON
      run: |
        pip3 install -r requirements.txt
        python3 tests/rws_tests.py
        python3 check_sites.py -i related_website_sets.JSON --with_diff --strict_formatting > results.txt
    - name: Read the result
      id: read_results
      uses: andstor/file-reader-action@v1
      with:
        path: "results.txt"
    - name: Failure Comment
      if: steps.read_results.outputs.contents != 'success'
      run: |
       echo "It appears you have failed some tests. Here are your results:" > message.txt
       cat results.txt >> message.txt
    - name: Sucess Comment
      if: steps.read_results.outputs.contents == 'success'
      run: echo "Looks like you've passed all of the checks!" > message.txt
    - name: Write Comment
      uses: mshick/add-pr-comment@v2
      with:   
        message-path: "message.txt" 
        refresh-message-position: true
    - name: Record Failure
      if: steps.read_results.outputs.contents != 'success'
      uses: actions/github-script@v3
      with:
        script: core.setFailed('This run has failed.')
